# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/abdulazizalahmadi/Desktop/Projects/NYTGames/Pips

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/abdulazizalahmadi/Desktop/Projects/NYTGames/Pips

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/abdulazizalahmadi/Desktop/Projects/NYTGames/Pips/CMakeFiles /Users/abdulazizalahmadi/Desktop/Projects/NYTGames/Pips//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/abdulazizalahmadi/Desktop/Projects/NYTGames/Pips/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named solver

# Build rule for target.
solver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 solver
.PHONY : solver

# fast build rule for target.
solver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/build
.PHONY : solver/fast

src/GAC.o: src/GAC.cpp.o
.PHONY : src/GAC.o

# target to build an object file
src/GAC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/GAC.cpp.o
.PHONY : src/GAC.cpp.o

src/GAC.i: src/GAC.cpp.i
.PHONY : src/GAC.i

# target to preprocess a source file
src/GAC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/GAC.cpp.i
.PHONY : src/GAC.cpp.i

src/GAC.s: src/GAC.cpp.s
.PHONY : src/GAC.s

# target to generate assembly for a file
src/GAC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/GAC.cpp.s
.PHONY : src/GAC.cpp.s

src/PipsSolver.o: src/PipsSolver.cpp.o
.PHONY : src/PipsSolver.o

# target to build an object file
src/PipsSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/PipsSolver.cpp.o
.PHONY : src/PipsSolver.cpp.o

src/PipsSolver.i: src/PipsSolver.cpp.i
.PHONY : src/PipsSolver.i

# target to preprocess a source file
src/PipsSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/PipsSolver.cpp.i
.PHONY : src/PipsSolver.cpp.i

src/PipsSolver.s: src/PipsSolver.cpp.s
.PHONY : src/PipsSolver.s

# target to generate assembly for a file
src/PipsSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/PipsSolver.cpp.s
.PHONY : src/PipsSolver.cpp.s

src/PipsState.o: src/PipsState.cpp.o
.PHONY : src/PipsState.o

# target to build an object file
src/PipsState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/PipsState.cpp.o
.PHONY : src/PipsState.cpp.o

src/PipsState.i: src/PipsState.cpp.i
.PHONY : src/PipsState.i

# target to preprocess a source file
src/PipsState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/PipsState.cpp.i
.PHONY : src/PipsState.cpp.i

src/PipsState.s: src/PipsState.cpp.s
.PHONY : src/PipsState.s

# target to generate assembly for a file
src/PipsState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/PipsState.cpp.s
.PHONY : src/PipsState.cpp.s

src/helpers.o: src/helpers.cpp.o
.PHONY : src/helpers.o

# target to build an object file
src/helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/helpers.cpp.o
.PHONY : src/helpers.cpp.o

src/helpers.i: src/helpers.cpp.i
.PHONY : src/helpers.i

# target to preprocess a source file
src/helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/helpers.cpp.i
.PHONY : src/helpers.cpp.i

src/helpers.s: src/helpers.cpp.s
.PHONY : src/helpers.s

# target to generate assembly for a file
src/helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/helpers.cpp.s
.PHONY : src/helpers.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... solver"
	@echo "... src/GAC.o"
	@echo "... src/GAC.i"
	@echo "... src/GAC.s"
	@echo "... src/PipsSolver.o"
	@echo "... src/PipsSolver.i"
	@echo "... src/PipsSolver.s"
	@echo "... src/PipsState.o"
	@echo "... src/PipsState.i"
	@echo "... src/PipsState.s"
	@echo "... src/helpers.o"
	@echo "... src/helpers.i"
	@echo "... src/helpers.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

